workspace(name = "bazel_integration_test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Fetch rules_nodejs so we can install our npm dependencies
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "cfc289523cf1594598215901154a6c2515e8bf3671fd708264a6f6aefe02bf39",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/4.4.6/rules_nodejs-4.4.6.tar.gz"],
)

# Fetch sass rules for compiling sass files
http_archive(
    name = "io_bazel_rules_sass",
    sha256 = "bd5c96d10271faa2ff33c85ff59f90ebd98be6c5d25a6937cd4ab6c4bde72b52",
    strip_prefix = "rules_sass-1.43.5",
    urls = [
        "https://github.com/bazelbuild/rules_sass/archive/1.43.5.zip",
        "https://mirror.bazel.build/github.com/bazelbuild/rules_sass/archive/1.43.5.zip",
    ],
)

# Check the bazel version and download npm dependencies
load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories", "yarn_install")

# Setup the Node.js toolchain
node_repositories(
    # Use same node version as root angular WORKSPACE since
    node_version = "16.10.0",
    yarn_version = "1.22.11",
)

# Install our npm dependencies into @npm
yarn_install(
    name = "npm",
    frozen_lockfile = False,
    package_json = "//:package.json",
    # Turn off symlink_node_modules here as it causes flakiness with missing
    # files in node_modules.
    # TODO: track down the root cause of the flakiness; current suspect is that
    # it is an issue with managed_directories when resources are limited
    symlink_node_modules = False,
    yarn_lock = "//:yarn.lock",
)

# Load protractor dependencies
load("@npm//@bazel/protractor:package.bzl", "npm_bazel_protractor_dependencies")

npm_bazel_protractor_dependencies()

# Setup the rules_webtesting toolchain
load("@io_bazel_rules_webtesting//web:repositories.bzl", "web_test_repositories")

web_test_repositories()

load("@io_bazel_rules_webtesting//web/versioned:browsers-0.3.2.bzl", "browser_repositories")

browser_repositories(
    chromium = True,
    firefox = True,
)

# Setup the rules_sass toolchain
load("@io_bazel_rules_sass//:defs.bzl", "sass_repositories")

sass_repositories()

load("@build_bazel_rules_nodejs//toolchains/esbuild:esbuild_repositories.bzl", "esbuild_repositories")

esbuild_repositories()
